FROM resin/%%RESIN_MACHINE_NAME%%-python

COPY ./requirements.txt /requirements.txt

RUN apt install vlc -y && apt install libav-tools -y && pip install -r /requirements.txt

COPY . /usr/src/app
WORKDIR /usr/src/app

CMD ["bash","start.sh"]
